### ISSUE TITLE
`stylin.rule` broken?

### ISSUE THREAD

**Issue by steadicat** [ajoslin/stylin#3]
[This line](https://github.com/ajoslin/stylin/blob/master/src/index.js#L35) calls [freeStyle#registerRule](https://github.com/blakeembrey/free-style#rules) with one parameter. Shouldn’t there be two? It looks like the `key` argument is completely dropped.

**Comment by ajoslin** [comment]
Indeed it is broken, thanks. Needs to be fixed with a test. I'll try to get to it today.
